### ISSUE TITLE
resolve issues with 'confirmable' breaking devise panels

### ISSUE THREAD

**Issue by mocxd** [GovLab/noi3#109]
such as edit account panel

**Comment by mocxd** [comment]
<img width="667" alt="screen shot 2016-10-06 at 4 54 31 am" src="https://cloud.githubusercontent.com/assets/1042629/19159474/aa5439d0-8bba-11e6-97ef-e936b245aa92.png">

error when clicking on edit account

**Comment by mocxd** [comment]
oh i guess this is fixed now maybe

**Comment by tekd** [comment]
There is a new issue with the  format js in Registrations#Create
