### ISSUE TITLE
signup form doesnt give any feedback or is not working

### ISSUE THREAD

**Issue by claudioccm** [GovLab/noi3#112]
check if email `gigeer27@gmail.com` is an existing account

**Comment by tekd** [comment]
Does not work in /users/sign_up and there is a server error

But works in panel 
![screen shot 2016-10-06 at 3 42 48 pm](https://cloud.githubusercontent.com/assets/9205941/19167886/9fb35120-8bdb-11e6-98cf-f050fa186e06.png)

**Comment by tekd** [comment]
Login button for mobile is also broken

**Comment by mocxd** [comment]
ill fix
