### ISSUE TITLE
match me panel has html structure issues

### ISSUE THREAD

**Issue by claudioccm** [GovLab/noi3#29]
Expertise Panel - View Skills should be a link

**Comment by claudioccm** [comment]
I realized this is happening because the app is not importing foundation.min.css

@mocxd: can you make sure foundation is pulled before any other stylesheet?

**Comment by mocxd** [comment]
ok well i just updated this panel so let me take a peek at this

**Comment by mocxd** [comment]
was this fixed once the foundation gem was implemented @claudioccm ?
