### ISSUE TITLE
Reverse order of projects, events, expertise on profile panel

### ISSUE THREAD

**Issue by naffis** [GovLab/noi3#79]

**Comment by mocxd** [comment]
i think this may be outdated, we have them possibly in the order we want now?

**Comment by mocxd** [comment]
<img width="386" alt="screen shot 2016-10-17 at 12 45 54 pm" src="https://cloud.githubusercontent.com/assets/1042629/19446642/ac5a34e0-9467-11e6-8564-2c988e2cbc8b.png">
